### ISSUE TITLE
Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by LouisJS** [react-community/react-navigation#2824]
### Current Behavior

When i'm trying to use react-navigation in my project.
I'm having : 

> _reactNative.Dimensions.addEventListener is not a function
>
> withOrientation.componentDidMount
> with.Orientation.js:37:17

It worked until really recently when i tried to remove my node_modules and install them again.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^1.0.0-beta.13",
| react-native     |   "0.42.x"
| node             |   v8.3.0
| npm or yarn      |   4.6.1

**Comment by spencercarli** [comment]
Can you ensure you're using the latest release? 1.0.0-beta.15

**Comment by kelset** [comment]
tbh you are almost 8 versions of react native behind, and probably some of the other libraries/nested dependencies have been updated to be compliant to newer versions.

That said, why do you think it's related to `react-navigation`? Can you post the complete error log?

**Comment by LouisJS** [comment]
Still not working with _"react-navigation": "^1.0.0-beta.15"_
And for compatibility issue, i'm stuck with react 0.42.x

**Comment by kelset** [comment]
> That said, why do you think it's related to react-navigation? Can you post the complete error log?

Can you please answers to those two questions?

That said, this is a library in beta - as probably many more you have been using in your project - so we cannot help you with such an old version of the main library :(

**Comment by LouisJS** [comment]
This is the 2 errors i have in the console of the React Native Debugger 

    ExceptionsManager.js:63 _reactNative.Dimensions.addEventListener is not a function
       handleException @ ExceptionsManager.js:63
       handleError @ InitializeCore.js:114
       reportFatalError @ error-guard.js:44
       guard @ MessageQueue.js:48
       callFunctionReturnFlushedQueue @ MessageQueue.js:107
       (anonymous) @ debuggerWorker.js:71
    Unhandled JS Exception: _reactNative.Dimensions.addEventListener is not a function
       reactConsoleErrorHandler @ ExceptionsManager.js:71
       console.error @ YellowBox.js:62
       logIfNoNativeHook @ RCTLog.js:38
       __callFunction @ MessageQueue.js:242
       (anonymous) @ MessageQueue.js:108
       guard @ MessageQueue.js:46
       callFunctionReturnFlushedQueue @ MessageQueue.js:107
       (anonymous) @ debuggerWorker.js:71

**Comment by LouisJS** [comment]
@kelset As i said, It was working before. I've just got this issue since in reinstalled my dependencies

**Comment by kelset** [comment]
> I've just got this issue since in reinstalled my dependencies

Then it's 100% related to some nested dependency of any of the libraries you are using in your project. So I don't understand why it should be `react-navigation` causing the issue (moreover, as you said, it was working before).

Unluckly in the `react-native` world you have to keep up with newer versions of the all the libraries you are using because even the main library is still in beta. So tbh you have no choice but to update to newer versions.

**Comment by kelset** [comment]
I don't know what you are trying to obtain @LouisJS by opening a clone issue (#2830).

Unless:
1. you can provide a reliable test project that reproduces the issue
2. you have **definitive proof** that it's caused by `react-navigation` - since the error log you posted states that it's caused by `react-native`

I won't re-open this issue. Again, you are using a really old version of the `react-native`, you should update.

**Comment by marcodefreitas** [comment]
I'm also having this issue today. My RN version is 0.42.0, node v8.1.2, npm v4.6.1 and react-navigation 1.0.0-beta.11.
I'm using a TabNavigator that when removed the error doesn't show. This can be a react-native issue since it refers to Dimensions but this only occurred when I did a fresh npm install.

**Comment by marcodefreitas** [comment]
Was able to fix this by updating a react-navigation dependency, react-native-tab-view to version 0.0.67.
Hope this helps.

**Comment by swl367** [comment]
Our team had the issue with react-navigation v1.0.0-beta.15. Downgrading to .11 resolved the issue.

**Comment by yusisi** [comment]
I have the same issue eith both react-navigation v1.0.0-beta.15 and  .11

**Comment by spencercarli** [comment]
The causes of this is the addition of `withOrientation` which helps the navbar work in a more consistent manner (though it will be replaced later). @swl367  @yusisi it seems this issue is related to having a vastly outdated version of React Native. What version are you running on?

If you're on 0.42 or below you'll run into issues because Dimensions.addEventListener wasn't added until 0.43. 0.43 came out in April.

**Comment by swl367** [comment]
Makes sense. I’m on 0.42.3

**Comment by adnanaliarshad** [comment]
I face similar issue and my  packages were:
```
react-native 0.42.3
react-navigation: 1.0.0-beta.26
```

I had to downgrade react-navigation to 1.0.0-beta.13 to fix this issue.

**Comment by javahuang** [comment]
```
TypeError: addListener is not a function

This error is located at:
    in CardStack (at CardStackTransitioner.js:66)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:151)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:38)
```
i face simiar issue too
my packages were:
```
"react-native": "0.52.0",
"react-navigation": "^1.0.0-beta.29",
```

I had to downgrade react-navigation to 1.0.0-beta.21 to fix this issue

**Comment by batical** [comment]
Same, downgrade to : 
 
> "1.0.0-beta.27"

**Comment by MAYDAY1993** [comment]
@adnanaliarshad thank you so much ,I've been stuck with this problem these two days.

```js

  "react-native": "0.42.3",
   "react-navigation": "^1.1.2"

```
downgrade **react-navigation** to: 

> 1.0.0-beta.13

works fine 😃

**Comment by Fsarmento** [comment]
I suddenly started having the same error after deleting node_modules and running "yarn install".

```
TypeError: addListener is not a function
ExceptionsManager.js:65
This error is located at:
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:39)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at Root.js:52)
    in AppWithNavigationState (created by Connect(AppWithNavigationState))
    in Connect(AppWithNavigationState) (at Root.js:74)
    in PersistGate (at Root.js:65)
    in Provider (at Root.js:64)
    in Root (at App.js:25)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
ExceptionsManager.js:73
Please check the code for the PersistGate component.

```


Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

"react-navigation": "^1.2.0"


I followed what @javahuang did and the error disappeared.

```
  render() {
    return (
      <AppNavigator
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav,
          addListener: () => {}                <-- Add this line
        })}
      />
    );
  }
```
