### ISSUE TITLE
upgrade expo 52 to 53 :_reactNative.BackHandler.removeEventListener is not a function (it is undefined), getting this error while navigating to home-screen in React react-native expo

### ISSUE THREAD

**Issue by AFDHAL2009** [react-community/react-navigation#12681]
### Current behavior

 "@react-navigation/bottom-tabs": "^7.4.2",
    "@react-navigation/material-top-tabs": "^7.3.2",
    "@react-navigation/native": "^7.1.14",
    "@react-navigation/native-stack": "^7.3.21",
    "@react-navigation/stack": "^7.4.2",
  "expo": "^53.0.19",
    "react-native": "0.79.5",

### Expected behavior

<img width="690" height="203" alt="Image" src="https://github.com/user-attachments/assets/58b36938-98f8-4652-841f-3ab8fd889e2d" />

### Reproduction

Upgrade expo 52 to 53

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by holmesjr** [comment]
Look in your node modules folder for any dependency that contains the call to BackHandler.removeEventListener. For example, I still have native-base and this is no longer maintained. This issue has a lot more details:


https://github.com/react-navigation/react-navigation/issues/12422

**Comment by AFDHAL2009** [comment]
"dependencies": {
    "@gorhom/bottom-sheet": "^5.1.2",
    "@gorhom/portal": "^1.0.14",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-clipboard/clipboard": "^1.13.2",
    "@react-native-community/datetimepicker": "8.4.1",
    "@react-native-community/slider": "4.5.6",
    "@react-native-google-signin/google-signin": "^11.0.1",
    "@react-navigation/bottom-tabs": "^7.4.2",
    "@react-navigation/material-top-tabs": "^7.3.2",
    "@react-navigation/native": "^7.1.14",
    "@react-navigation/native-stack": "^7.3.21",
    "@react-navigation/stack": "^7.4.2",
    "@reduxjs/toolkit": "^2.0.1",
    "@shopify/flash-list": "1.7.6",
    "@tanstack/react-query": "^5.75.2",
    "axios": "^1.6.5",
    "date-fns": "^3.3.0",
    "expo": "^53.0.19",
    "expo-apple-authentication": "~7.2.4",
    "expo-application": "~6.1.5",
    "expo-blur": "~14.1.5",
    "expo-build-properties": "~0.14.8",
    "expo-camera": "~16.1.10",
    "expo-checkbox": "~4.1.4",
    "expo-clipboard": "~7.1.5",
    "expo-constants": "~17.1.7",
    "expo-contacts": "~14.2.5",
    "expo-dev-client": "~5.2.4",
    "expo-device": "~7.1.4",
    "expo-document-picker": "~13.1.6",
    "expo-file-system": "~18.1.11",
    "expo-font": "~13.3.2",
    "expo-image": "~2.3.2",
    "expo-image-manipulator": "~13.1.7",
    "expo-image-picker": "~16.1.4",
    "expo-linear-gradient": "~14.1.5",
    "expo-linking": "~7.1.7",
    "expo-local-authentication": "~16.0.5",
    "expo-localization": "~16.1.6",
    "expo-location": "~18.1.6",
    "expo-media-library": "~17.1.7",
    "expo-notifications": "~0.31.4",
    "expo-sharing": "~13.1.5",
    "expo-splash-screen": "~0.30.10",
    "expo-status-bar": "~2.2.3",
    "expo-tracking-transparency": "~5.2.4",
    "expo-updates": "~0.28.17",
    "expo-web-browser": "~14.2.0",
    "getenv": "^2.0.0",
    "i18n-iso-countries": "^7.14.0",
    "i18next": "^23.7.18",
    "jwt-decode": "^4.0.0",
    "moment": "^2.30.1",
    "onesignal-expo-plugin": "^2.0.3",
    "react": "19.0.0",
    "react-i18next": "^14.0.1",
    "react-native": "0.79.5",
    "react-native-autocomplete-dropdown": "^4.4.0",
    "react-native-calendars": "^1.1303.0",
    "react-native-collapsible": "^1.6.1",
    "react-native-country-flag": "^2.0.2",
    "react-native-device-info": "^14.0.0",
    "react-native-fbsdk-next": "^13.0.0",
    "react-native-gesture-bottom-sheet": "^1.1.0",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-maps": "^1.20.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-modalize": "^2.1.1",
    "react-native-onesignal": "^5.2.12",
    "react-native-pager-view": "6.7.1",
    "react-native-reanimated": "~3.17.4",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "^0.0.27",
    "react-native-root-siblings": "^5.0.1",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-size-matters": "^0.4.2",
    "react-native-svg": "^15.11.2",
    "react-native-switch-selector": "^2.3.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-walkthrough-tooltip": "^1.6.0",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1",
    "use-debounce": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/babel__core": "^7.20.5",
    "@types/react": "~19.0.10",
    "@types/react-native-dotenv": "~0.2.2",
    "@types/react-native-fbsdk": "~3.0.6",
    "@types/react-native-vector-icons": "^6.4.18",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "prettier": "3.4.2",
    "react-native-dotenv": "^3.4.9",
    "typescript": "~5.8.3"
  },
  "private": true
}
this all module that I used also I handled   useEffect(() => {
    const backAction = () => {
      Alert.alert("Hold on!", "Are you sure you want to go back?", [
        {
          text: "Cancel",
          onPress: () => null,
          style: "cancel",
        },
        { text: "YES", onPress: () => BackHandler.exitApp() },
      ]);
      return true;
    };

    const backHandler = BackHandler.addEventListener(
      "hardwareBackPress",
      backAction
    );

    return () => backHandler.remove();
  }, []);

**Comment by bekzzz** [comment]
I've came across this issue while upgrading expo to 53. 
I was getting this error on an UI where I would call a Modal component (React Native)
[back-handler RN Docs](https://reactnative.dev/docs/backhandler)
[define onRequestClose at Modal component](https://reactnative.dev/docs/modal#onrequestclose)

Sharing in case anyone comes across a similiar issue

**Comment by AFDHAL2009** [comment]
using minimal example with bottom tab it was working fine without **BackHandler** import React from "react";
import { View, Text, Button } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createStackNavigator } from "@react-navigation/stack";

const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Booking"
        onPress={() => navigation.navigate("Booking")}
      />
    </View>
  );
}

function BookingScreen({ navigation }) {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Booking Screen</Text>
      <Button
        title="Go to Account"
        onPress={() => navigation.navigate("Account")}
      />
    </View>
  );
}

function AccountScreen() {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Account Screen</Text>
    </View>
  );
}

// 📌 Stack navigator for Booking + Account
function BookingStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Booking" component={BookingScreen} />
      <Stack.Screen name="Account" component={AccountScreen} />
    </Stack.Navigator>
  );
}

// 📌 Main App
export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen
          name="BookingTab"
          component={BookingStack}
          options={{ title: "Booking" }}
        />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
this confirm that the issue may due to BackHandler or Something like that

**Comment by AFDHAL2009** [comment]
****

> I've came across this issue while upgrading expo to 53. I was getting this error on an UI where I would call a Modal component (React Native) [back-handler RN Docs](https://reactnative.dev/docs/backhandler) [define onRequestClose at Modal component](https://reactnative.dev/docs/modal#onrequestclose)
> 
> Sharing in case anyone comes across a similiar issue

That is true the import Modal from "react-native-modal"; <Modal
      statusBarTranslucent
      // presentationStyle="formSheet"
      scrollTo={handleScrollTo}
      isVisible={!!modal}
      animationIn={animationIn}
      animationOut={animationOut}
      animationInTiming={500}
      animationOutTiming={500}
      backdropTransitionInTiming={800}
      backdropTransitionOutTiming={800}
      onSwipeComplete={() => closeModal()}
      scrollOffset={scrollOffset}
      swipeDirection={swipeDirection}
      backdropColor="transparent"
      scrollOffsetMax={400 - 300}
      propagateSwipe={true} create same issue

**Comment by Rajputsachi** [comment]
Facing same issue

ERROR Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

This error is located at:

22 |
23 | // Form States

24 | const [description, setDescription] = useState('');
| ^
25 | const [leadIds, setLeadIds] = useState('');
26 | const [files, setFiles] = useState([] as any);
27 | const descriptionInput = useRef();

Call Stack
BugReport (app/dashboard/home/bug-report.tsx:24:51)
Home (app/dashboard/tabs/home/index.tsx:52:47)
ScreenContentWrapper ()
RNSScreenStack ()
Layout(./dashboard/tabs/home/_layout.tsx) ()
Layout (app/dashboard/tabs/_layout.tsx:79:31)
ScreenContentWrapper ()
RNSScreenStack ()
AuthProvider (@generics/providers/auth.provider.tsx:72:25)
AppProvider (@generics/providers/app.provider.tsx:18:39)
LayOut (app/_layout.tsx:48:46)
MaintenanceProvider (@generics/providers/maintenance.provider.tsx:6:47)
Layout (app/_layout.tsx:21:44)
RNCSafeAreaProvider ()
App ()
ErrorOverlay ()

but i am not using removeEventListener in my project.

I am using Expo: 53.0.9, react-native: 0.79.5 and react: 19.0.0

Is any thing i missed here @AFDHAL2009 @bekzzz?

**Comment by AFDHAL2009** [comment]
This due to react-native-modal i had also encounter same with , try update
it or check some third party that cause this issue!

Le jeu. 17 juil. 2025, 05:40, Rajputsachi ***@***.***> a
écrit :

**Comment by Rvydkybs** [comment]
For anyone who is facing this issue, i also upgraded my expo version from 52 to 53. I got the same error. in my case , i did not use react-native-modal package but i searched in my project and i found this ;
`import { Modal as PaperModal, Portal } from 'react-native-paper';`
So i upgrade the react-native-paper package with `npm i react-native-paper@latest` and it works just fine ! 🔥

**Comment by cbdeveloper** [comment]
I got the same. It seems that there was a breaking change in RN's `BackHandler`. Not sure in which version, but I got the error after upgrading from Expo 52 to 53, which bumped RN from `0.76.8` to `0.79.5` for me.

`BackHandler.removeEventListener` does not exist anymore.

https://reactnative.dev/docs/backhandler

I had to refactor from this:

```
return () => BackHandler.removeEventListener('hardwareBackPress', handleBackPress);
```

To this:

```
useEffect(() => {
  const handleBackPress = () => { // Handle it };
  const backHandler = BackHandler.addEventListener('hardwareBackPress', handleBackPress);
  return () => backHandler.remove();
},[]);
```

**Comment by mirshanv** [comment]
I recently upgraded my React Native Expo project from SDK 52 to SDK 53. After upgrading, I am getting the following error when navigating to my home screen:

_reactNative.BackHandler.removeEventListener is not a function (it is undefined)

This error occurs during navigation, specifically when navigating between screens or when the screen mounts/unmounts.



Expo SDK: 53

React Native: (auto-installed with Expo 53)

React Navigation: v6

Platform: Android (also testing on Expo Go)

What I tried

Cleared cache:

npx expo start -c

Reinstalled node_modules:

rm -rf node_modules
npm install

Checked navigation setup and BackHandler usage.


Has anyone faced this issue after upgrading to Expo SDK 53?

Is BackHandler.removeEventListener deprecated or changed in newer React Native versions, and what is the correct way to remove the event listener now?

Any help would be appreciated.
