### ISSUE TITLE
Crash when overriding tabBarComponent

### ISSUE THREAD

**Issue by spencercarli** [react-community/react-navigation#2592]
### Current Behavior

Upon setting a custom `tabBarComponent` the app crashes with the following error

```
getOnPress is not a function. (In 'getOnPress(scene)', 'getOnPress' is undefined)
```

![simulator screen shot - iphone x - 2017-09-15 at 09 32 15](https://user-images.githubusercontent.com/1105429/30487334-cbbeb17a-99f8-11e7-872b-87fa9e31296b.png)

### Expected Behavior

The app should not crash. The error is caused by fe4b1e2379244da8b4909a707760417c06b04452 and should be a simple fix by setting a default function [here](https://github.com/react-community/react-navigation/blob/fe4b1e2379244da8b4909a707760417c06b04452/src/views/TabView/TabView.js#L104).

### Your Environment
- _Include as many relevant details about the environment you experienced the bug in_

| software         | version
| ---------------- | -------
| react-navigation | react-navigation@fe4b1e2379244da8b4909a707760417c06b04452
| react-native     |  0.48.3
| node             | v8.3.0
| npm or yarn      | 0.27.5 (yarn)

**Comment by spencercarli** [comment]
Nevermind, my proposed solution wouldn't work. We should check for the existence of `getOnPress` inside of `TabBarBottom` and `TabBarTop`.

**Comment by spencercarli** [comment]
User error - I was trying things from master but was using the last npm release. Doh!

**Comment by DiegoFranciscoHG** [comment]
Apparently this still an issue, I get a crash that is very alike:

![26038048_1520001571381721_949007085_o](https://user-images.githubusercontent.com/34254918/34333341-46eb34fc-e901-11e7-86ed-235d221de2c2.png)

**Comment by MuhammadSNajib** [comment]
+1

**Comment by kritinvij** [comment]
Can we reopen this issue? Still having problems overriding the TabBarBottom component.
