### ISSUE TITLE
[BETA-14] _reactNative.Dimensions.addEventListener is not a function

### ISSUE THREAD

**Issue by LouisJS** [react-community/react-navigation#2830]
I'm working with react-native 0.42.X (obliged for compatibility reason) and everything was fine while i was using react-navigation in **1.0.0-beta-13**
I tried to update to newer version, and i identified an issue since  **> beta-14**

### Current Behavior

    ExceptionsManager.js:63 _reactNative.Dimensions.addEventListener is not a function 
      handleException @ ExceptionsManager.js:63
      handleError @ InitializeCore.js:114
      reportFatalError @ error-guard.js:44
      guard @ MessageQueue.js:48
      callFunctionReturnFlushedQueue @ MessageQueue.js:107
      (anonymous) @ debuggerWorker.js:71
    Unhandled JS Exception: _reactNative.Dimensions.addEventListener is not a function
      reactConsoleErrorHandler @ ExceptionsManager.js:71
      console.error @ YellowBox.js:62
      logIfNoNativeHook @ RCTLog.js:38
      __callFunction @ MessageQueue.js:242
      (anonymous) @ MessageQueue.js:108
      guard @ MessageQueue.js:46
      callFunctionReturnFlushedQueue @ MessageQueue.js:107
      (anonymous) @ debuggerWorker.js:71

### Expected Behavior

 I suspect a regression between the beta-13 release en beta-14. Concerning Dimensions uses (orientation, ect).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0.beta-14
| react-native     |   0.42.X
| node             |    v8.3.0
| npm or yarn      |    4.6.1

**Comment by kelset** [comment]
Duplicate of #2824
