### ISSUE TITLE
Build Failed after updated to 3.0.8 

### ISSUE THREAD

**Issue by sliultron** [react-community/react-navigation#5395]
### Current Behavior

Updated React-Navigation to 3.0.8 and followed the instruction to install the react-native-gesture-handler.
after react-native link react-native-gesture-handler
i got error when building with react-native run-ios or building in the xCode.
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNForceTouchHandler", referenced from:

      objc-class-ref in libRNGestureHandler.a(RNGestureHandlerManager.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Behavior

should be compiled without problem

### How to reproduce

tried clear node_modules and package.lock.json
reinstalled react-navigation and react-native-gesture-handler
tried react-native link and manually link
got same error

### Your Environment
```
    "react": "16.6.3",
    "react-native": "0.57.3",
    "react-native-gesture-handler": "1.0.12",
    "react-navigation": "3.0.8"
```

**Comment by nschurmann** [comment]
this should be reopened, having same issue just updating and cleaning my build.

**Comment by brentvatne** [comment]
this is not related to react-navigation @nschurmann - we can't help everybody with the native configuration of the project's dependencies. try googling the error.

**Comment by brentvatne** [comment]
ta da google https://github.com/kmagiera/react-native-gesture-handler/issues/387
